#!/usr/bin/env python3
"""fieldnotes.py — field notes for a Hermes Agent installation.

Three independent parts that share one store of Markdown notes:

  notes      pitfalls with root cause and workaround: new, search, index, lint
  patches    local edits of the Hermes core, checked read-only against the
             live install after every `hermes update`: patches, check, drift, doctor
  dashboard  one pinned Telegram message, edited in place, with the state of
             the core, the patches and the notes

The script never edits the Hermes core and never runs patch scripts. Standard
library only, Python >= 3.11. Run `fieldnotes.py --help` for the commands.

Exit codes: 0 fine · 1 usage or lint errors · 2 a patch is MISSING ·
3 a patch is UNKNOWN (the check could not decide) · 4 store or core not found.
"""

from __future__ import annotations

import sys

sys.dont_write_bytecode = True

import argparse  # noqa: E402
import datetime as dt  # noqa: E402
import fnmatch  # noqa: E402
import hashlib  # noqa: E402
import html  # noqa: E402
import json  # noqa: E402
import os  # noqa: E402
import re  # noqa: E402
import subprocess  # noqa: E402
import time  # noqa: E402
import urllib.error  # noqa: E402
import urllib.request  # noqa: E402
from pathlib import Path  # noqa: E402

VERSION = "1.1.0"
SCHEMA_VERSION = 1
SKILL_DIR = Path(__file__).resolve().parents[1]
ASSETS = SKILL_DIR / "assets"
KNOWN_PITFALLS = SKILL_DIR / "references" / "known-pitfalls.md"
INDEX_MARKER = "<!-- fieldnotes:index — everything below is generated by `fieldnotes.py index` -->"

TYPES = ("pitfall", "patch", "observation")
AREAS = ("gateway", "platform", "cron", "skills", "memory", "mcp", "tools", "providers",
         "config", "update", "plugins", "dashboard", "other")
STATUSES = ("active", "workaround", "fixed-upstream", "obsolete", "promoted", "needs-verification")
LIVE_STATUSES = ("active", "workaround", "needs-verification")
PATCH_KINDS = ("bugfix", "customization", "workaround")
REQUIRED = ("schema_version", "id", "title", "date", "type", "area", "status", "summary")
REQUIRED_PATCH = ("patch_kind", "patch_short")

EXIT_OK, EXIT_ERR, EXIT_MISSING, EXIT_UNKNOWN, EXIT_NOTFOUND = 0, 1, 2, 3, 4

DEFAULTS = {
    "store_dir": "",
    "hermes_root": "",
    "patch_scripts_base": "",
    "timezone": "UTC",
    "language": "en",
    "drift": {"ignore_globs": ["**/__pycache__/**", "*.pyc", "*.orig", "*.rej", "*.bak", "*.bak-*",
                               "*.pre-*"]},
    "dashboard": {"enabled": False, "chat_id": "", "thread_id": "", "pin": True,
                  "bot_token_env": "TELEGRAM_BOT_TOKEN", "freshness_hours": 6, "max_patches": 40},
    "alerts": {"repeat_hours": 24},
    "watch": {"timeout_sec": 180},
    "upstream": {"check": True, "repo": "NousResearch/hermes-agent", "branch": "main", "check_hours": 12},
}

SECRET_PATTERNS = [
    ("openai-style key", re.compile(r"\bsk-[A-Za-z0-9_-]{20,}")),
    ("github token", re.compile(r"\b(ghp|gho|ghs|ghu)_[A-Za-z0-9]{30,}|\bgithub_pat_[A-Za-z0-9_]{30,}")),
    ("slack token", re.compile(r"\bxox[abposr]-[A-Za-z0-9-]{10,}")),
    ("aws key id", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("private key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("telegram bot token", re.compile(r"\b\d{8,10}:[A-Za-z0-9_-]{35}\b")),
    ("bearer token", re.compile(r"\bBearer\s+[A-Za-z0-9._~+/-]{20,}")),
]


class FieldNotesError(Exception):
    """A problem the user must fix (bad path, bad config); printed without a traceback."""

    def __init__(self, message, code=EXIT_ERR):
        super().__init__(message)
        self.code = code


# ---------------------------------------------------------------------------
# time
# ---------------------------------------------------------------------------

def _tz(name):
    try:
        from zoneinfo import ZoneInfo
        return ZoneInfo(name), True
    except Exception:  # noqa: BLE001 — no tz database (e.g. Windows without tzdata)
        return dt.timezone.utc, name.upper() == "UTC"


def now_utc():
    override = os.environ.get("FIELDNOTES_NOW")  # tests only: ISO timestamp
    if override:
        return dt.datetime.fromisoformat(override).astimezone(dt.timezone.utc)
    return dt.datetime.now(dt.timezone.utc)


def iso(ts):
    return ts.astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_ts(value):
    if not value:
        return None
    try:
        return dt.datetime.fromisoformat(str(value).replace("Z", "+00:00")).astimezone(dt.timezone.utc)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# configuration and paths
# ---------------------------------------------------------------------------

def _merge(base, extra):
    out = dict(base)
    for key, value in (extra or {}).items():
        if key.startswith("_"):
            continue  # "_comment" keys of the example file
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _merge(out[key], value)
        else:
            out[key] = value
    return out


class Context:
    """Resolved paths and settings. Precedence everywhere: CLI > env > config file > default."""

    def __init__(self, args):
        explicit_home = getattr(args, "hermes_home", None)
        env_home = os.environ.get("HERMES_HOME")
        if explicit_home:
            self.home = Path(explicit_home).expanduser()
            if not self.home.is_dir():
                raise FieldNotesError(f"--hermes-home does not exist: {self.home}", EXIT_NOTFOUND)
        elif env_home:
            self.home = Path(env_home).expanduser()
        else:
            self.home = Path(os.path.expanduser("~/.hermes"))

        explicit_cfg = getattr(args, "config", None) or os.environ.get("FIELDNOTES_CONFIG")
        self.config_path = Path(explicit_cfg).expanduser() if explicit_cfg else self.home / "field-notes.json"
        file_cfg = {}
        if self.config_path.is_file():
            try:
                file_cfg = json.loads(self.config_path.read_text(encoding="utf-8-sig"))
            except ValueError as exc:
                raise FieldNotesError(f"config is not valid JSON: {self.config_path}: {exc}")
            if not isinstance(file_cfg, dict):
                raise FieldNotesError(f"config must be a JSON object: {self.config_path}")
        elif explicit_cfg:
            raise FieldNotesError(f"config not found: {self.config_path}", EXIT_NOTFOUND)
        self.cfg = _merge(DEFAULTS, file_cfg)

        env_map = {"store_dir": "FIELDNOTES_STORE_DIR", "hermes_root": "FIELDNOTES_HERMES_ROOT",
                   "timezone": "FIELDNOTES_TIMEZONE", "language": "FIELDNOTES_LANGUAGE"}
        for key, var in env_map.items():
            value = os.environ.get(var)
            if value:
                self.cfg[key] = value
        if not os.environ.get("FIELDNOTES_STORE_DIR") and os.environ.get("FIELD_NOTES_DIR") \
                and not file_cfg.get("store_dir"):
            self.cfg["store_dir"] = os.environ.get("FIELD_NOTES_DIR")

        root = getattr(args, "root", None) or self.cfg.get("store_dir") or str(self.home / "field-notes")
        self.store = Path(root).expanduser()
        hroot = getattr(args, "hermes_root", None) or self.cfg.get("hermes_root") or str(self.home / "hermes-agent")
        self.hermes_root = Path(hroot).expanduser()
        self.read_only = bool(getattr(args, "read_only", False))
        self.state_path = self.home / "cache" / "field-notes-state.json"
        self.lock_path = self.home / "cache" / "field-notes.lock"
        self.tz, self.tz_ok = _tz(str(self.cfg.get("timezone") or "UTC"))
        lang = str(self.cfg.get("language") or "en").lower()
        self.lang = lang if lang in STRINGS else "en"

    @property
    def notes_dir(self):
        return self.store / "notes"

    def require_writable(self, what):
        if self.read_only:
            raise FieldNotesError(f"--read-only: refusing to {what}")

    def local(self, ts):
        return ts.astimezone(self.tz)

    def today(self):
        return self.local(now_utc()).date()


def read_env_value(home, name):
    """Value of NAME from the process environment, else from $HERMES_HOME/.env."""
    value = os.environ.get(name)
    if value:
        return value.strip()
    env_file = home / ".env"
    try:
        lines = env_file.read_text(encoding="utf-8-sig").splitlines()
    except OSError:
        return ""
    for line in lines:
        m = re.match(r"\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$", line)
        if not m or m.group(1) != name:
            continue
        raw = m.group(2).strip()
        if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
            raw = raw[1:-1]
        else:
            raw = re.sub(r"\s+#.*$", "", raw)
        return raw.strip()
    return ""


# ---------------------------------------------------------------------------
# state and lock
# ---------------------------------------------------------------------------

class Lock:
    """O_CREAT|O_EXCL lock file next to the state; a lock older than `stale` seconds is broken."""

    def __init__(self, path, stale=600, wait=30):
        self.path, self.stale, self.wait = Path(path), stale, wait
        self.held = False

    def __enter__(self):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        deadline = time.monotonic() + self.wait
        while True:
            try:
                fd = os.open(str(self.path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.write(fd, str(os.getpid()).encode())
                os.close(fd)
                self.held = True
                return self
            except FileExistsError:
                try:
                    age = time.time() - self.path.stat().st_mtime
                except OSError:
                    continue
                if age > self.stale:
                    try:
                        self.path.unlink()
                    except OSError:
                        pass
                    continue
                if time.monotonic() > deadline:
                    raise FieldNotesError(f"another fieldnotes run holds {self.path}")
                time.sleep(0.2)

    def __exit__(self, *exc):
        if self.held:
            try:
                self.path.unlink()
            except OSError:
                pass


def atomic_write(path, text, mode=None):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp{os.getpid()}")
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    if mode is not None:
        try:
            os.chmod(tmp, mode)
        except OSError:
            pass
    os.replace(tmp, path)


def load_state(ctx):
    """State dict; a corrupt file is moved aside and a fresh state starts (reported in `_recovered`)."""
    empty = {"schema_version": SCHEMA_VERSION, "core": {"history": []}, "last_check": None,
             "alerts": {}, "dashboard": {}}
    path = ctx.state_path
    if not path.is_file():
        return empty
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError("not an object")
    except (OSError, ValueError) as exc:
        if not ctx.read_only:
            try:
                os.replace(path, path.with_name(path.name + ".corrupt"))
            except OSError:
                pass
        empty["_recovered"] = f"state file was unreadable ({exc}); started a new one"
        return empty
    for key, value in empty.items():
        data.setdefault(key, value)
    data["core"].setdefault("history", [])
    return data


def save_state(ctx, state):
    if ctx.read_only:
        return
    clean = {k: v for k, v in state.items() if not k.startswith("_")}
    atomic_write(ctx.state_path, json.dumps(clean, ensure_ascii=False, indent=1) + "\n", 0o600)


# ---------------------------------------------------------------------------
# frontmatter: a flat YAML subset that yaml.safe_load also reads
# ---------------------------------------------------------------------------

_KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*)\s*:(?:\s+(.*))?$")
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_BARE_OK = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.\-/]*$")
_NUMBER_LIKE = re.compile(r"^[-+]?(\d[\d_]*\.?\d*|\.\d+)([eE][-+]?\d+)?$|^0[xXoObB]")
_YAML_WORDS = {"yes", "no", "on", "off", "true", "false", "null", "y", "n", "~"}


def _strip_comment(raw):
    out, quote = [], None
    for i, ch in enumerate(raw):
        if quote:
            out.append(ch)
            if ch == quote and not (quote == '"' and i and raw[i - 1] == "\\"):
                quote = None
            continue
        if ch in "\"'":
            quote = ch
        elif ch == "#" and (i == 0 or raw[i - 1] in " \t"):
            break
        out.append(ch)
    return "".join(out).strip()


def _unquote(token):
    token = token.strip()
    if len(token) >= 2 and token[0] == token[-1] == '"':
        try:
            return json.loads(token)
        except ValueError:
            return token[1:-1]
    if len(token) >= 2 and token[0] == token[-1] == "'":
        return token[1:-1].replace("''", "'")
    return token


def _split_list(inner):
    items, buf, quote = [], [], None
    for ch in inner:
        if quote:
            buf.append(ch)
            if ch == quote:
                quote = None
            continue
        if ch in "\"'":
            quote = ch
            buf.append(ch)
        elif ch == ",":
            items.append("".join(buf))
            buf = []
        else:
            buf.append(ch)
    if "".join(buf).strip():
        items.append("".join(buf))
    return [_unquote(i) for i in items if i.strip()]


def parse_value(raw):
    raw = _strip_comment(raw or "")
    if raw.startswith("[") and raw.endswith("]"):
        return _split_list(raw[1:-1])
    return _unquote(raw)


def split_frontmatter(text):
    """(meta, keys_in_order, body, errors). Notes without frontmatter return an empty meta."""
    text = text.lstrip("\ufeff").replace("\r\n", "\n")
    if not text.startswith("---\n"):
        return {}, [], text, ["no frontmatter (file must start with '---')"]
    end = text.find("\n---", 4)
    if end == -1:
        return {}, [], text, ["frontmatter is not closed with '---'"]
    block = text[4:end]
    rest = text[end + 4:]
    body = rest[1:] if rest.startswith("\n") else rest
    meta, order, errors = {}, [], []
    for n, line in enumerate(block.split("\n"), start=2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[0] in " \t":
            errors.append(f"line {n}: nested or indented values are not supported")
            continue
        m = _KEY_RE.match(line)
        if not m:
            errors.append(f"line {n}: expected 'key: value'")
            continue
        key = m.group(1)
        if key in meta:
            errors.append(f"line {n}: duplicate key '{key}'")
            continue
        meta[key] = parse_value(m.group(2) or "")
        order.append(key)
    return meta, order, body, errors


def format_scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    text = "" if value is None else str(value)
    if _DATE_RE.match(text):
        return text
    if (_BARE_OK.match(text) and re.search(r"[A-Za-z]", text) and text.lower() not in _YAML_WORDS
            and not _NUMBER_LIKE.match(text)):
        return text
    return json.dumps(text, ensure_ascii=False)


def dump_frontmatter(meta, order=None):
    keys = list(order or []) + [k for k in meta if k not in (order or [])]
    lines = ["---"]
    for key in keys:
        if key not in meta:
            continue
        value = meta[key]
        if isinstance(value, (list, tuple)):
            lines.append(f"{key}: [{', '.join(format_scalar(v) for v in value)}]")
        else:
            lines.append(f"{key}: {format_scalar(value)}")
    lines.append("---")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# notes
# ---------------------------------------------------------------------------

class Note:
    def __init__(self, path):
        self.path = Path(path)
        self.id = self.path.stem
        try:
            self.text = self.path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            self.text = ""
            self.meta, self.order, self.body, self.errors = {}, [], "", [f"unreadable: {exc}"]
            return
        self.meta, self.order, self.body, self.errors = split_frontmatter(self.text)

    def get(self, key, default=""):
        value = self.meta.get(key, default)
        return default if value is None else value

    @property
    def title(self):
        return str(self.get("title") or self.id)

    @property
    def type(self):
        return str(self.get("type") or "pitfall")

    @property
    def status(self):
        return str(self.get("status") or "active")

    @property
    def is_patch(self):
        return self.type == "patch"

    @property
    def is_live(self):
        return self.status in LIVE_STATUSES

    @property
    def checks_path(self):
        return self.path.with_name(self.id + ".checks.json")

    def date(self, key="date"):
        value = str(self.get(key) or "")
        try:
            return dt.date.fromisoformat(value)
        except ValueError:
            return None


def load_notes(ctx):
    if not ctx.notes_dir.is_dir():
        return []
    return [Note(p) for p in sorted(ctx.notes_dir.glob("*.md"))]


def require_store(ctx):
    if not ctx.notes_dir.is_dir():
        raise FieldNotesError(f"no field notes store at {ctx.store} — run `fieldnotes.py init`", EXIT_NOTFOUND)


# ---------------------------------------------------------------------------
# core identity, version, history
# ---------------------------------------------------------------------------

_VERSION_RE = re.compile(r'^version\s*=\s*"([^"]+)"', re.MULTILINE)


def version_tuple(text):
    m = re.match(r"^\s*v?(\d+)\.(\d+)(?:\.(\d+))?", str(text or ""))
    if not m:
        return None
    return tuple(int(x or 0) for x in m.groups())


def _git(root, *argv, timeout=20):
    # --no-optional-locks: never refresh the index, so a status/diff stays read-only.
    try:
        proc = subprocess.run(["git", "--no-optional-locks", "-C", str(root), *argv],
                              capture_output=True, text=True, timeout=timeout, stdin=subprocess.DEVNULL)
    except (OSError, subprocess.SubprocessError):
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout


def core_info(ctx):
    root = ctx.hermes_root
    info = {"root": str(root), "exists": root.is_dir(), "version": None, "identity": None,
            "identity_source": None, "short": None, "describe": None, "tag": None, "ahead": None,
            "is_git": False, "bootstrapped_at": None}
    if not info["exists"]:
        return info
    pyproject = root / "pyproject.toml"
    try:
        text = pyproject.read_text(encoding="utf-8")
        m = _VERSION_RE.search(text)
        info["version"] = m.group(1) if m else None
    except OSError:
        text = None
    head = _git(root, "rev-parse", "HEAD")
    if head and re.match(r"^[0-9a-f]{40}$", head.strip()):
        info.update(is_git=True, identity=head.strip(), identity_source="git", short=head.strip()[:7])
        when = _git(root, "log", "-1", "--format=%cI", "HEAD")
        info["commit_date"] = when.strip()[:10] if when else None
        desc = _git(root, "describe", "--tags", "--long")
        if desc:
            desc = desc.strip()
            m = re.match(r"^(.*)-(\d+)-g[0-9a-f]+$", desc)
            if m:
                info.update(describe=desc, tag=m.group(1), ahead=int(m.group(2)))
    elif text is not None:
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
        info.update(identity="pyproject:" + digest[:16], identity_source="pyproject-hash", short=digest[:7])
    # Version display: a dev build (0.0.0) is named by its tag when there is one.
    if info["version"] in (None, "0.0.0") and info["tag"]:
        m = re.search(r"v?(\d+\.\d+(?:\.\d+)?)", info["tag"])
        if m:
            info["version_from_tag"] = m.group(1)
    info["bootstrapped_at"] = _bootstrap_time(ctx.home, info["identity"])
    return info


def display_version(core):
    return core.get("version_from_tag") or core.get("version") or "?"


def _bootstrap_time(home, identity):
    """Hermes records each install revision it bootstrapped (internal format, used as a hint only)."""
    if not identity:
        return None
    for path in sorted((home / "installs").glob("*/bootstrap/*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8-sig"))
        except (OSError, ValueError):
            continue
        if isinstance(data, dict) and data.get("identity") == identity and data.get("bootstrappedAt"):
            ts = parse_ts(str(data["bootstrappedAt"]))
            if ts is None:
                m = re.match(r"^(.*[+-]\d{2})(\d{2})$", str(data["bootstrappedAt"]))
                ts = parse_ts(f"{m.group(1)}:{m.group(2)}") if m else None
            if ts:
                return iso(ts)
    return None


def record_core(state, core, now):
    """Append the core identity to the history when it changed. Returns the event or None."""
    history = state["core"]["history"]
    if not core.get("identity"):
        return None
    if history and history[-1].get("identity") == core["identity"]:
        return None
    seen_before = any(h.get("identity") == core["identity"] for h in history)
    previous = history[-1] if history else None
    history.append({"identity": core["identity"], "version": display_version(core),
                    "first_seen_at": iso(now), "bootstrapped_at": core.get("bootstrapped_at")})
    del history[:-50]
    if previous is None:
        return None
    return {"kind": "core_rollback" if seen_before else "core_changed",
            "old": previous.get("version"), "old_short": short_identity(previous.get("identity")),
            "new": display_version(core), "new_short": core.get("short")}


def short_identity(identity):
    identity = str(identity or "")
    return identity[len("pyproject:"):][:7] if identity.startswith("pyproject:") else identity[:7]


def updated_at(state, core):
    """(timestamp, source) of the current core: Hermes' own bootstrap record, else first seen by us."""
    if core.get("bootstrapped_at"):
        return parse_ts(core["bootstrapped_at"]), "bootstrap"
    for item in reversed(state["core"]["history"]):
        if item.get("identity") == core.get("identity"):
            return parse_ts(item.get("first_seen_at")), "first-seen"
    return None, None


def previous_core(state, core):
    history = state["core"]["history"]
    for i in range(len(history) - 1, -1, -1):
        if history[i].get("identity") == core.get("identity") and i > 0:
            return history[i - 1]
    return None


# ---------------------------------------------------------------------------
# patch checks
# ---------------------------------------------------------------------------

def safe_target(root, rel):
    """Resolved path of `rel` inside `root`, or None if it escapes the root."""
    rel = str(rel or "").replace("\\", "/")
    if not rel or rel.startswith("/") or re.match(r"^[A-Za-z]:", rel) or ".." in rel.split("/"):
        return None
    root_res = Path(root).resolve()
    path = (Path(root) / rel)
    try:
        resolved = path.resolve()
    except OSError:
        return None
    try:
        resolved.relative_to(root_res)
    except ValueError:
        return None
    return path


def validate_checks(data):
    """List of problems in a parsed checks.json."""
    problems = []
    if not isinstance(data, dict):
        return ["checks file must be a JSON object"]
    editions = data.get("editions")
    if not isinstance(editions, list) or not editions:
        return ["'editions' must be a non-empty list"]
    for i, ed in enumerate(editions):
        where = f"editions[{i}]"
        if not isinstance(ed, dict):
            problems.append(f"{where} must be an object")
            continue
        when = ed.get("when", {})
        if not isinstance(when, dict) or set(when) - {"min_version", "max_version"}:
            problems.append(f"{where}.when may only hold min_version / max_version")
        else:
            for key in ("min_version", "max_version"):
                if when.get(key) and version_tuple(when[key]) is None:
                    problems.append(f"{where}.when.{key} is not a version")
        targets = ed.get("targets")
        if not isinstance(targets, list) or not targets:
            problems.append(f"{where}.targets must be a non-empty list")
            targets = []
        for j, t in enumerate(targets + list(ed.get("upstream") or [])):
            label = f"{where}.targets[{j}]" if j < len(targets) else f"{where}.upstream[{j - len(targets)}]"
            if not isinstance(t, dict) or not isinstance(t.get("file"), str) or not t.get("file"):
                problems.append(f"{label} needs a 'file'")
                continue
            if safe_target(".", t["file"]) is None:
                problems.append(f"{label}.file must be relative to the core root, without '..'")
            for key in ("contains", "not_contains"):
                value = t.get(key, [])
                if not isinstance(value, list) or not all(isinstance(s, str) and s for s in value):
                    problems.append(f"{label}.{key} must be a list of non-empty strings")
            if j < len(targets) and not t.get("contains"):
                problems.append(f"{label}.contains must name at least one sign of the patch")
    return problems


def _edition_for(editions, version):
    """(edition, reason). First edition whose bounds hold wins."""
    vt = version_tuple(version) if version and version != "0.0.0" else None
    bounded = [e for e in editions if (e.get("when") or {}).get("min_version") or (e.get("when") or {}).get("max_version")]
    if vt is None:
        if not bounded:
            return editions[0], None
        unbounded = [e for e in editions if e not in bounded]
        return (unbounded[0], None) if unbounded else (None, "version_unknown")
    for ed in editions:
        when = ed.get("when") or {}
        lo, hi = version_tuple(when.get("min_version")), version_tuple(when.get("max_version"))
        if (lo is None or vt >= lo) and (hi is None or vt <= hi):
            return ed, None
    return None, "n/a"


def _read(path):
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def check_patch(note, core, root):
    """Static check of one patch note against the core tree. Returns a result dict."""
    result = {"id": note.id, "short": str(note.get("patch_short") or note.title), "kind": str(note.get("patch_kind")),
              "status": "UNKNOWN", "reason": None, "evidence": [], "targets": []}
    try:
        data = json.loads(note.checks_path.read_text(encoding="utf-8-sig"))
    except OSError:
        result["reason"] = "bad_checks"
        result["evidence"].append(f"no checks file {note.checks_path.name}")
        return result
    except ValueError as exc:
        result["reason"] = "bad_checks"
        result["evidence"].append(f"{note.checks_path.name}: {exc}")
        return result
    problems = validate_checks(data)
    if problems:
        result["reason"] = "bad_checks"
        result["evidence"].extend(problems)
        return result
    version = core.get("version_from_tag") or core.get("version")
    edition, why = _edition_for(data["editions"], version)
    if edition is None:
        if why == "n/a":
            result["status"] = "N/A"
            result["evidence"].append(f"no edition applies to {version}")
        else:
            result["reason"] = "version_unknown"
        return result
    result["targets"] = [t["file"] for t in edition["targets"]]
    gone, unreadable, full, partial, absent = [], [], [], [], []
    for t in edition["targets"]:
        path = safe_target(root, t["file"])
        if path is None:
            unreadable.append(t["file"])
            result["evidence"].append(f"{t['file']}: path escapes the core root")
            continue
        if not path.is_file():
            gone.append(t["file"])
            result["evidence"].append(f"{t['file']}: file not found")
            continue
        text = _read(path)
        if text is None:
            unreadable.append(t["file"])
            continue
        found = [s for s in t["contains"] if s in text]
        forbidden = [s for s in t.get("not_contains", []) if s in text]
        missing = [s for s in t["contains"] if s not in text]
        line = f"{t['file']}: {len(found)}/{len(t['contains'])} signs"
        if forbidden:
            line += f", unpatched code present: {', '.join(repr(s[:40]) for s in forbidden)}"
        result["evidence"].append(line)
        if not missing and not forbidden:
            full.append(t["file"])
        elif not found:
            absent.append(t["file"])
        else:
            partial.append(t["file"])
    upstream_rules = edition.get("upstream") or []
    upstream_ok = bool(upstream_rules)
    for rule in upstream_rules:
        path = safe_target(root, rule["file"])
        text = _read(path) if path is not None and path.is_file() else None
        if text is None or not all(s in text for s in rule.get("contains", [])):
            upstream_ok = False
    if upstream_ok:
        result["evidence"].append("upstream signs present")

    if unreadable:
        result["reason"] = "unreadable"
    elif gone:
        if upstream_ok:
            result["status"] = "UPSTREAMED"
        else:
            result["reason"] = "target_gone"
    elif partial:
        result["reason"] = "partial"
    elif full and len(full) == len(edition["targets"]):
        if upstream_ok:
            result["reason"] = "conflict"
        else:
            result["status"] = "OK"
    elif absent and len(absent) == len(edition["targets"]):
        result["status"] = "UPSTREAMED" if upstream_ok else "MISSING"
    else:
        result["reason"] = "partial"  # some targets full, others absent
    return result


def check_patches(ctx, notes, core):
    results = []
    for note in notes:
        if note.is_patch and note.is_live:
            results.append(check_patch(note, core, ctx.hermes_root))
    return results


def patches_exit(results):
    if any(r["status"] == "UNKNOWN" for r in results):
        return EXIT_UNKNOWN
    if any(r["status"] == "MISSING" for r in results):
        return EXIT_MISSING
    return EXIT_OK


# ---------------------------------------------------------------------------
# drift: core changes and whether patch notes cover them
# ---------------------------------------------------------------------------

def _ignored(path, globs):
    name = path.rsplit("/", 1)[-1]
    return any(fnmatch.fnmatch(path, g) or fnmatch.fnmatch(name, g) for g in globs)


def compute_drift(ctx, core, results):
    out = {"available": False, "reason": None, "changed": [], "registered": [], "unregistered": [],
           "untracked": [], "ahead": core.get("ahead"), "tag": core.get("tag")}
    if not core.get("exists"):
        out["reason"] = "core not found"
        return out
    if not core.get("is_git"):
        out["reason"] = "core is not a git checkout"
        return out
    changed = _git(ctx.hermes_root, "diff", "HEAD", "--name-only", "--no-renames")
    untracked = _git(ctx.hermes_root, "ls-files", "--others", "--exclude-standard")
    if changed is None or untracked is None:
        out["reason"] = "git failed"
        return out
    globs = list((ctx.cfg.get("drift") or {}).get("ignore_globs") or [])
    out["available"] = True
    out["changed"] = [p for p in changed.splitlines() if p and not _ignored(p, globs)]
    out["untracked"] = [p for p in untracked.splitlines() if p and not _ignored(p, globs)][:200]
    covered = {t for r in results for t in r.get("targets", [])}
    out["registered"] = [p for p in out["changed"] if p in covered]
    out["unregistered"] = [p for p in out["changed"] if p not in covered]
    return out


# ---------------------------------------------------------------------------
# lint
# ---------------------------------------------------------------------------

def lint(ctx, notes, core=None):
    """List of (level, where, message); level is 'error', 'warn' or 'stale'."""
    out = []
    ids = {}
    for note in notes:
        where = f"notes/{note.path.name}"
        for err in note.errors:
            out.append(("error", where, err))
        if not note.meta:
            continue
        m = note.meta
        for key in REQUIRED:
            if m.get(key) in (None, "", []):
                out.append(("error", where, f"missing '{key}'"))
        if note.is_patch:
            for key in REQUIRED_PATCH:
                if m.get(key) in (None, ""):
                    out.append(("error", where, f"patch note missing '{key}'"))
        checks = [("type", TYPES), ("area", AREAS), ("status", STATUSES)]
        if note.is_patch:
            checks.append(("patch_kind", PATCH_KINDS))
        for key, allowed in checks:
            if m.get(key) and m.get(key) not in allowed:
                out.append(("error", where, f"{key} '{m.get(key)}' not one of: {', '.join(allowed)}"))
        if str(m.get("id") or "") and str(m.get("id")) != note.id:
            out.append(("error", where, f"id '{m.get('id')}' differs from the file name '{note.id}'"))
        for key in ("date", "updated", "verified_at"):
            if m.get(key) and note.date(key) is None:
                out.append(("error", where, f"{key} must be YYYY-MM-DD"))
        if note.date("updated") and note.date("date") and note.date("updated") < note.date("date"):
            out.append(("error", where, "updated is earlier than date"))
        if not re.match(r"^\d{4}-\d{2}-\d{2}-[a-z0-9][a-z0-9-]*$", note.id):
            out.append(("warn", where, "file name should be YYYY-MM-DD-slug.md"))
        for key in ("title", "summary"):
            if re.match(r"^\s*<.*>\s*$", str(m.get(key) or "")):
                out.append(("warn", where, f"{key} is still the template placeholder"))
        if "{{" in note.text:
            out.append(("warn", where, "template placeholders '{{…}}' left in the note"))
        if len(str(m.get("summary") or "")) > 1000:
            out.append(("warn", where, "summary is longer than 1000 characters — it is one line of the index"))
        if note.is_patch and note.is_live:
            if m.get("patch_kind") in ("customization", "workaround") and not m.get("upstream") \
                    and not m.get("upstream_none_reason"):
                out.append(("warn", where, "no upstream link: add upstream_none_reason"))
            if not note.checks_path.is_file():
                out.append(("error", where, f"no {note.checks_path.name} — the patch cannot be checked"))
            else:
                try:
                    problems = validate_checks(json.loads(note.checks_path.read_text(encoding="utf-8-sig")))
                except ValueError as exc:
                    problems = [f"not valid JSON: {exc}"]
                for p in problems:
                    out.append(("error", f"notes/{note.checks_path.name}", p))
        ids.setdefault(note.id[11:], []).append(note.id)
        for link in re.findall(r"\]\(([^)\s#]+\.md)(?:#[^)]*)?\)", note.body):
            if "://" in link:
                continue
            if not (note.path.parent / link).resolve().is_file():
                out.append(("warn", where, f"broken link: {link}"))
        for label, pattern in SECRET_PATTERNS:
            if pattern.search(note.text):
                out.append(("error", where, f"looks like a secret ({label}) — mask it"))
        if core and core.get("identity") and note.is_live and m.get("verified_identity"):
            vid = str(m.get("verified_identity"))
            if not core["identity"].startswith(vid) and not str(core.get("short") or "").startswith(vid):
                out.append(("stale", where, f"verified on {vid}, core is now {core.get('short')}"))
    for slug, same in ids.items():
        if len(same) > 1:
            out.append(("warn", "notes/", f"same slug '{slug}' in {', '.join(same)} — update one note instead"))
    index = ctx.store / "INDEX.md"
    if notes:
        current = index.read_text(encoding="utf-8") if index.is_file() else ""
        if render_index(notes, current) != current.replace("\r\n", "\n"):
            out.append(("warn", "INDEX.md", "out of date — run `fieldnotes.py index`"))
    return out


# ---------------------------------------------------------------------------
# index
# ---------------------------------------------------------------------------

INDEX_HEAD = """# Field Notes

Pitfalls with root cause, local patches of the Hermes core, and observations worth keeping.
Each note is a file in `notes/`; its metadata lives in the frontmatter.
Kept by the `hermes-field-notes` skill. Text above the marker line is yours to edit.

"""


def _cell(text):
    return str(text or "").replace("|", "\\|").replace("\n", " ").strip()


def _index_head(current):
    """Text above the generated table: everything above the marker; for an index written by hand
    before this skill, everything above its first table header row; else the default intro."""
    current = current.replace("\r\n", "\n")
    if INDEX_MARKER in current:
        return current.split(INDEX_MARKER)[0]
    lines = current.split("\n")
    for i, line in enumerate(lines):
        if re.match(r"^\|\s*(date|дата)\s*\|", line, re.IGNORECASE):
            head = "\n".join(lines[:i]).rstrip()
            return head + "\n" if head else INDEX_HEAD
    return INDEX_HEAD


def render_index(notes, current=""):
    head = _index_head(current)
    rows = []
    for note in sorted(notes, key=lambda n: (str(n.get("date") or ""), n.id), reverse=True):
        date = str(note.get("date") or "?")
        if note.get("updated") and str(note.get("updated")) != date:
            date += f" · upd. {str(note.get('updated'))[5:]}"
        rows.append(f"| {date} | [{_cell(note.title)}](notes/{note.path.name}) | {_cell(note.type)} | "
                    f"{_cell(note.get('area'))} | {_cell(note.status)} | {_cell(note.get('summary'))} |")
    table = ["| Date | Note | Type | Area | Status | Summary |", "|---|---|---|---|---|---|", *rows]
    return head.rstrip("\n") + "\n\n" + INDEX_MARKER + "\n\n" + "\n".join(table) + "\n"


# ---------------------------------------------------------------------------
# search
# ---------------------------------------------------------------------------

def _tokens(text):
    return [t for t in re.findall(r"[\w.:/-]+", str(text).lower()) if len(t) > 1]


def known_pitfalls():
    """[(title, text)] entries of the bundled known-pitfalls reference."""
    try:
        text = KNOWN_PITFALLS.read_text(encoding="utf-8")
    except OSError:
        return []
    parts = re.split(r"^### +", text, flags=re.MULTILINE)[1:]
    out = []
    for part in parts:
        title, _, rest = part.partition("\n")
        out.append((title.strip(), rest.strip()))
    return out


def search(notes, terms, limit=10):
    words = [w.lower() for w in terms if w.strip()]
    hits = []
    for note in notes:
        fields = [(note.title, 3), (note.get("summary"), 2), (" ".join(note.get("tags") or []), 2),
                  (note.get("area"), 1), (note.body, 1)]
        score = 0
        for text, weight in fields:
            low = str(text or "").lower()
            score += sum(weight * low.count(w) for w in words if w in low)
        if score and all(any(w in str(t or "").lower() for t, _ in fields) for w in words):
            hits.append((score, "note", note))
    for title, text in known_pitfalls():
        low_t, low_b = title.lower(), text.lower()
        if all(w in low_t or w in low_b for w in words):
            score = sum(3 * low_t.count(w) + low_b.count(w) for w in words)
            hits.append((score, "known", (title, text)))
    hits.sort(key=lambda h: -h[0])
    return hits[:limit], len(notes), len(known_pitfalls())


# ---------------------------------------------------------------------------
# upstream: latest Hermes release and how far the installed core is from it
# ---------------------------------------------------------------------------

def _github_get(path, timeout=15):
    """GET https://api.github.com/<path> without credentials (60 requests/hour per IP is plenty)."""
    req = urllib.request.Request(f"https://api.github.com/{path}",
                                 headers={"Accept": "application/vnd.github+json",
                                          "User-Agent": "hermes-field-notes"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


GITHUB_GET = _github_get  # replaced in tests


def _release_version(release):
    for text in (release.get("name") or "", release.get("tag_name") or ""):
        m = re.search(r"v?(\d+\.\d+\.\d+)", text)
        if m and not re.match(r"^\d{4}\.", m.group(1)):
            return m.group(1)
    return release.get("tag_name")


def fetch_upstream(ctx, core):
    """Latest stable release, how the core relates to it, and how far main has moved on."""
    up = ctx.cfg.get("upstream") or {}
    repo = str(up.get("repo") or "NousResearch/hermes-agent")
    branch = str(up.get("branch") or "main")
    releases = GITHUB_GET(f"repos/{repo}/releases?per_page=10")
    latest = next((r for r in releases if not r.get("draft") and not r.get("prerelease")), None)
    info = {"latest": None, "relation": None, "behind_release": None, "behind_main": None}
    if latest:
        info["latest"] = {"tag": latest.get("tag_name"), "version": _release_version(latest),
                          "date": str(latest.get("published_at") or "")[:10]}
    sha = core.get("identity") if core.get("identity_source") == "git" else None
    if sha and latest:
        cmp = GITHUB_GET(f"repos/{repo}/compare/{latest['tag_name']}...{sha}")
        status = cmp.get("status")
        info["relation"] = {"identical": "same", "ahead": "newer", "behind": "older",
                            "diverged": "diverged"}.get(status)
        info["behind_release"] = cmp.get("behind_by")
    elif latest and version_tuple(core.get("version")) and version_tuple(info["latest"]["version"]):
        mine, theirs = version_tuple(core["version"]), version_tuple(info["latest"]["version"])
        info["relation"] = "same" if mine == theirs else ("newer" if mine > theirs else "older")
    if sha:
        cmp = GITHUB_GET(f"repos/{repo}/compare/{sha}...{branch}")
        info["behind_main"] = cmp.get("ahead_by")
    return info


def upstream_info(ctx, state, core, allow_network=True):
    """Cached upstream info (refreshed every upstream.check_hours) and alert events."""
    up = ctx.cfg.get("upstream") or {}
    if not up.get("check", True) or os.environ.get("FIELDNOTES_OFFLINE"):
        return {"enabled": False}, []
    cache = dict(state.get("upstream") or {})
    now = now_utc()
    hours = float(up.get("check_hours") or 12)
    fetched = parse_ts(cache.get("fetched_at"))
    fresh = fetched and (now - fetched).total_seconds() < hours * 3600 \
        and cache.get("identity") == core.get("identity")
    events = []
    if not fresh and allow_network and not ctx.read_only:
        previous_tag = ((cache.get("info") or {}).get("latest") or {}).get("tag")
        try:
            info = fetch_upstream(ctx, core)
            cache = {"fetched_at": iso(now), "identity": core.get("identity"), "info": info, "error": None}
            new_tag = (info.get("latest") or {}).get("tag")
            if previous_tag and new_tag and new_tag != previous_tag:
                events.append({"kind": "new_release", "v": info["latest"]["version"], "date": info["latest"]["date"]})
        except Exception as exc:  # noqa: BLE001 — network or API shape; keep the last good answer
            cache["error"] = f"{type(exc).__name__}: {str(exc)[:120]}"
            cache["fetched_at"] = iso(now)  # do not hammer the API; retry after check_hours
            cache.setdefault("identity", core.get("identity"))
        state["upstream"] = cache
    return {"enabled": True, **(cache.get("info") or {}), "error": cache.get("error"),
            "fetched_at": cache.get("fetched_at")}, events


# ---------------------------------------------------------------------------
# dashboard: strings, report, render
# ---------------------------------------------------------------------------

STRINGS = {
    "en": {
        "v_ok": "all good ✅", "v_missing": "❌ {n} patch(es) lost — re-apply needed",
        "v_attention": "⚠️ needs a look: {what}", "v_new": "🆕 Hermes {v} is out",
        "w_unknown": "{n} patch check(s) undecided", "w_upstream": "{n} patch(es) already fixed in Hermes",
        "w_drift": "{n} core edit(s) without a patch note", "w_core": "core not found",
        "core": "⚙️ Hermes core", "version_release": "Version {v} · release of {d}",
        "version_main": "Version {v} · build from main of {d}", "version_plain": "Version {v}",
        "installed": "Installed {d} — {ago}", "seen_since": "Tracked since {d}",
        "rel_same": "Latest release: you have it ✅", "rel_newer": "Newer than the latest release {v} ({d})",
        "rel_older": "🆕 New release: {v} ({d}) — you are on {mine}",
        "rel_diverged": "Branch differs from release {v} ({d})",
        "main_behind": "main has moved on by {n} {w} since your build", "w_commit": ("commit", "commits", "commits"),
        "main_same": "Same commit as current main",
        "up_error": "Could not check for updates ({err})",
        "drift": "⚠️ {n} core file(s) edited without a patch note — those edits vanish on the next update",
        "local_commits": "⚠️ {n} local commit(s) on top of the installed version",
        "patches": "🩹 My patches: {n}", "no_patches": "🩹 No patches — the core is unmodified",
        "g_MISSING": "❌ Lost after an update — {n}, re-apply:", "g_UNKNOWN": "❔ Could not check — {n}:",
        "g_UPSTREAMED": "⬆️ Already fixed in Hermes — {n}, can be retired:", "g_OK": "✅ Working — {n}:",
        "g_N/A": "⏸ Not needed on this version — {n}:",
        "r_partial": "only part of the edit is there", "r_conflict": "both the patch and Hermes' own fix are there",
        "r_target_gone": "the file is gone from the core", "r_version_unknown": "core version unclear",
        "r_bad_checks": "its check description is broken", "r_unreadable": "file cannot be read",
        "notes": "📒 Notes: {n}", "n_new": "+{n} this month", "n_stale": "re-check after the update: {n}",
        "n_unc": "unconfirmed: {n}",
        "legend": "✅ works · ❌ lost after an update · ⬆️ fixed in Hermes itself · ❔ check undecided",
        "footer": "Checked {when} · refreshed hourly", "footer_lint": " · ⚠️ errors in notes: {n} (fieldnotes lint)",
        "ago_days": "{n} d ago", "ago_today": "today", "ago_1": "yesterday", "tz_note": " (UTC)",
        "a_core_changed": "🔄 Hermes core updated: {old} ({old_short}) → {new} ({new_short})",
        "a_core_rollback": "↩️ Hermes core rolled back: {old} ({old_short}) → {new} ({new_short})",
        "a_patch_MISSING": "❌ Patch «{p}» is lost — re-apply it: {cmd}",
        "a_patch_UNKNOWN": "❔ Patch «{p}»: check undecided ({reason})",
        "a_patch_UPSTREAMED": "⬆️ Patch «{p}» looks fixed in Hermes — confirm and mark it fixed-upstream",
        "a_patch_back": "✅ Patch «{p}» works again",
        "a_drift_new": "⚠️ Core files changed outside the patch registry: {files}",
        "a_drift_clear": "✅ No core changes outside the registry any more",
        "a_dash_recreated": "📌 The dashboard message was gone — posted and pinned again",
        "a_pin_failed": "📌 Cannot pin the dashboard: {err}",
        "a_bot_failing": "⚠️ Dashboard update keeps failing: {err}",
        "a_send_uncertain": "⚠️ Dashboard send got no answer; not retrying for {h} h to avoid a duplicate",
        "a_state_recovered": "⚠️ field-notes: {msg}",
        "a_core_missing": "⚠️ field-notes: Hermes core not found at {root} — patches are not checked",
        "a_no_store": "⚠️ field-notes: no notes store at {root} — run scripts/install.py",
        "a_new_release": "🆕 Hermes {v} released ({date}) — read the notes, then update and run doctor",
        "cmd_none": "see the note",
    },
    "ru": {
        "v_ok": "всё в порядке ✅", "v_missing": "❌ слетело патчей: {n} — нужно переприменить",
        "v_attention": "⚠️ нужно посмотреть: {what}", "v_new": "🆕 вышел Hermes {v}",
        "w_unknown": "не проверено патчей: {n}", "w_upstream": "уже исправлено в Hermes: {n}",
        "w_drift": "правок ядра без описания: {n}", "w_core": "ядро не найдено",
        "core": "⚙️ Ядро Hermes", "version_release": "Версия {v} · релиз от {d}",
        "version_main": "Версия {v} · сборка из main от {d}", "version_plain": "Версия {v}",
        "installed": "Установлена {d} — {ago}", "seen_since": "Отслеживается с {d}",
        "rel_same": "Последний релиз: он и стоит ✅", "rel_newer": "Новее последнего релиза {v} (от {d})",
        "rel_older": "🆕 Вышел релиз {v} (от {d}) — у тебя {mine}",
        "rel_diverged": "Ветка расходится с релизом {v} (от {d})",
        "main_behind": "Свежий main ушёл вперёд на {n} {w}", "w_commit": ("коммит", "коммита", "коммитов"),
        "main_same": "Совпадает с текущим main",
        "up_error": "Проверить обновления не удалось ({err})",
        "drift": "⚠️ Файлов ядра изменено без описания патча: {n} — эти правки пропадут при обновлении",
        "local_commits": "⚠️ Локальных коммитов поверх установленной версии: {n}",
        "patches": "🩹 Мои патчи: {n}", "no_patches": "🩹 Своих патчей нет — ядро без правок",
        "g_MISSING": "❌ Слетели после обновления — {n}, переприменить:", "g_UNKNOWN": "❔ Не удалось проверить — {n}:",
        "g_UPSTREAMED": "⬆️ Уже исправлено в самом Hermes — {n}, можно снять:", "g_OK": "✅ Работают — {n}:",
        "g_N/A": "⏸ Не нужны на этой версии — {n}:",
        "r_partial": "правка на месте лишь частично", "r_conflict": "есть и патч, и исправление Hermes",
        "r_target_gone": "файл исчез из ядра", "r_version_unknown": "не ясна версия ядра",
        "r_bad_checks": "ошибка в описании проверки", "r_unreadable": "файл не читается",
        "notes": "📒 Заметки: {n}", "n_new": "+{n} за месяц", "n_stale": "перепроверить после обновления: {n}",
        "n_unc": "не подтверждено: {n}",
        "legend": "✅ работает · ❌ слетел после обновления · ⬆️ исправлено в самом Hermes · ❔ проверка не уверена",
        "footer": "Проверено {when} · обновляется каждый час", "footer_lint": " · ⚠️ ошибок в заметках: {n} (fieldnotes lint)",
        "ago_days": "{n} дн назад", "ago_today": "сегодня", "ago_1": "вчера", "tz_note": " (UTC)",
        "a_core_changed": "🔄 Ядро Hermes обновлено: {old} ({old_short}) → {new} ({new_short})",
        "a_core_rollback": "↩️ Ядро Hermes откатилось: {old} ({old_short}) → {new} ({new_short})",
        "a_patch_MISSING": "❌ Патч «{p}» слетел — переприменить: {cmd}",
        "a_patch_UNKNOWN": "❔ Патч «{p}»: проверка не решила ({reason})",
        "a_patch_UPSTREAMED": "⬆️ Патч «{p}», похоже, исправлен в самом Hermes — подтвердить и пометить fixed-upstream",
        "a_patch_back": "✅ Патч «{p}» снова работает",
        "a_drift_new": "⚠️ Файлы ядра изменены мимо реестра патчей: {files}",
        "a_drift_clear": "✅ Изменений ядра вне реестра больше нет",
        "a_dash_recreated": "📌 Сообщение дашборда пропало — отправлено и закреплено заново",
        "a_pin_failed": "📌 Не удалось закрепить дашборд: {err}",
        "a_bot_failing": "⚠️ Дашборд не обновляется: {err}",
        "a_send_uncertain": "⚠️ Отправка дашборда без ответа; повтор не раньше чем через {h} ч, чтобы не было дубля",
        "a_state_recovered": "⚠️ field-notes: {msg}",
        "a_core_missing": "⚠️ field-notes: ядро Hermes не найдено в {root} — патчи не проверяются",
        "a_no_store": "⚠️ field-notes: нет хранилища заметок в {root} — запусти scripts/install.py",
        "a_new_release": "🆕 Вышел Hermes {v} ({date}) — прочитать список изменений, обновиться и запустить doctor",
        "cmd_none": "см. заметку",
    },
}

STATUS_ICON = {"OK": "✅", "MISSING": "❌", "UNKNOWN": "❔", "UPSTREAMED": "⬆️", "N/A": "⏸"}
STATUS_ORDER = {"MISSING": 0, "UNKNOWN": 1, "UPSTREAMED": 2, "OK": 3, "N/A": 4}


def build_report(ctx, state, notes, core, results, drift, lint_items, upstream=None):
    now = now_utc()
    today = ctx.today()
    live = [n for n in notes if n.is_live]
    patch_notes = {n.id: n for n in notes if n.is_patch}
    rows = []
    for r in results:
        note = patch_notes.get(r["id"])
        rows.append({"id": r["id"], "status": r["status"], "reason": r.get("reason"),
                     "label": str((note.get("patch_what") if note else "") or r["short"]),
                     "upstream": str(note.get("upstream") or "") if note else ""})
    rows.sort(key=lambda r: (STATUS_ORDER.get(r["status"], 9), r["label"].lower()))
    counts = {k: sum(1 for r in rows if r["status"] == k) for k in STATUS_ICON}
    stale = 0
    if core.get("identity"):
        for n in live:
            vid = str(n.get("verified_identity") or "")
            if vid and not core["identity"].startswith(vid) and not str(core.get("short") or "").startswith(vid):
                stale += 1
    upd, upd_src = updated_at(state, core)
    unregistered = len(drift.get("unregistered") or []) if drift.get("available") else 0
    if not core.get("exists"):
        verdict = ("attention", ["core"])
    elif counts["MISSING"]:
        verdict = ("missing", [])
    else:
        reasons = []
        if counts["UNKNOWN"]:
            reasons.append(("unknown", counts["UNKNOWN"]))
        if counts["UPSTREAMED"]:
            reasons.append(("upstream", counts["UPSTREAMED"]))
        if unregistered:
            reasons.append(("drift", unregistered))
        verdict = ("attention", reasons) if reasons else ("ok", [])
    return {
        "generated_at": iso(now),
        "verdict": verdict,
        "core": {"exists": core.get("exists"), "version": display_version(core), "short": core.get("short"),
                 "commit_date": core.get("commit_date"), "tag": core.get("tag"), "ahead": core.get("ahead") or 0,
                 "installed_at": iso(upd) if upd else None, "installed_source": upd_src},
        "upstream": upstream or {"enabled": False},
        "drift": {"available": drift.get("available"), "unregistered": unregistered},
        "patches": {"total": len(rows), "counts": counts, "rows": rows},
        "notes": {"total": len(notes),
                  "new_30d": sum(1 for n in notes if n.date() and (today - n.date()).days <= 30),
                  "stale": stale,
                  "unconfirmed": sum(1 for n in notes if n.status == "needs-verification")},
        "lint": {"errors": sum(1 for i in lint_items if i[0] == "error"),
                 "warnings": sum(1 for i in lint_items if i[0] == "warn")},
    }


def _fmt_dt(ctx, ts, with_time=True):
    local = ctx.local(ts)
    text = local.strftime("%d.%m %H:%M" if with_time else "%d.%m")
    is_utc = not ctx.tz_ok or str(ctx.cfg.get("timezone") or "UTC").upper() == "UTC"
    return text + (STRINGS[ctx.lang]["tz_note"] if is_utc and with_time else "")


def _fmt_day(value):
    try:
        return dt.date.fromisoformat(str(value)[:10]).strftime("%d.%m.%Y")
    except ValueError:
        return str(value or "?")


def _ago(ctx, ts):
    days = (ctx.today() - ctx.local(ts).date()).days
    s = STRINGS[ctx.lang]
    if days <= 0:
        return s["ago_today"]
    return s["ago_1"] if days == 1 else s["ago_days"].format(n=days)


def _issue_ref(url):
    m = re.search(r"/(?:issues|pull)/(\d+)", url or "")
    return f"#{m.group(1)}" if m else ("↗" if url else "")


def _plural(n, forms):
    """forms = (one, few, many); English uses one/many, Russian all three."""
    n = abs(int(n))
    if n % 10 == 1 and n % 100 != 11:
        return forms[0]
    if 2 <= n % 10 <= 4 and not 12 <= n % 100 <= 14:
        return forms[1]
    return forms[2]


def _num(n):
    return f"{n:,}".replace(",", " ") if isinstance(n, int) else str(n)


def render(ctx, report, fmt="telegram"):
    """(text, content_hash). The hash leaves out the 'checked at' footer."""
    s = STRINGS[ctx.lang]
    tg = fmt == "telegram"
    esc = (lambda t: html.escape(str(t), quote=False)) if tg else (lambda t: str(t))
    if tg:
        bold = lambda t: f"<b>{t}</b>"  # noqa: E731
    elif fmt == "md":
        bold = lambda t: f"**{t}**"  # noqa: E731
    else:
        bold = lambda t: t  # noqa: E731
    core, up, pt, nt = report["core"], report["upstream"], report["patches"], report["notes"]

    # 1. verdict line — what the pinned bar shows
    kind, reasons = report["verdict"]
    if kind == "ok":
        verdict = s["v_ok"]
    elif kind == "missing":
        verdict = s["v_missing"].format(n=pt["counts"]["MISSING"])
    else:
        parts = [s["w_core"] if r == "core" else s["w_" + r[0]].format(n=r[1]) for r in reasons]
        verdict = s["v_attention"].format(what=", ".join(parts))
    first = f"🩺 Hermes {esc(core['version'])} — {esc(verdict)}"
    if up.get("enabled") and up.get("relation") == "older" and up.get("latest"):
        first += " · " + esc(s["v_new"].format(v=up["latest"]["version"]))

    # 2. core
    lines = [bold(esc(s["core"]))]
    if core.get("exists"):
        build = None
        if up.get("relation") == "same":
            build = "release"
        elif up.get("relation") in ("newer", "diverged") and core.get("commit_date"):
            build = "main"
        if build == "release":
            lines.append(esc(s["version_release"].format(v=core["version"], d=_fmt_day(core.get("commit_date")))))
        elif build == "main":
            lines.append(esc(s["version_main"].format(v=core["version"], d=_fmt_day(core["commit_date"]))))
        else:
            lines.append(esc(s["version_plain"].format(v=core["version"])))
        if core.get("installed_at"):
            ts = parse_ts(core["installed_at"])
            if core.get("installed_source") == "bootstrap":
                lines.append(esc(s["installed"].format(d=_fmt_day(ctx.local(ts).date().isoformat()), ago=_ago(ctx, ts))))
            else:
                lines.append(esc(s["seen_since"].format(d=_fmt_day(ctx.local(ts).date().isoformat()))))
        if up.get("enabled"):
            latest = up.get("latest") or {}
            rel = up.get("relation")
            if rel == "same":
                lines.append(esc(s["rel_same"]))
            elif rel == "newer" and latest:
                lines.append(esc(s["rel_newer"].format(v=latest["version"], d=_fmt_day(latest["date"]))))
            elif rel == "older" and latest:
                lines.append(bold(esc(s["rel_older"].format(v=latest["version"], d=_fmt_day(latest["date"]),
                                                            mine=core["version"]))))
            elif rel == "diverged" and latest:
                lines.append(esc(s["rel_diverged"].format(v=latest["version"], d=_fmt_day(latest["date"]))))
            if up.get("behind_main"):
                lines.append(esc(s["main_behind"].format(n=_num(up["behind_main"]),
                                                         w=_plural(up["behind_main"], s["w_commit"]))))
            elif up.get("behind_main") == 0:
                lines.append(esc(s["main_same"]))
            if up.get("error") and not latest:
                lines.append(esc(s["up_error"].format(err=up["error"][:60])))
        if report["drift"].get("unregistered"):
            lines.append(esc(s["drift"].format(n=report["drift"]["unregistered"])))
        if core.get("ahead"):
            lines.append(esc(s["local_commits"].format(n=core["ahead"])))
    else:
        lines.append(esc(s["w_core"]))
    sections = [first, "\n".join(lines)]

    # 3. patches, grouped; the OK list folds away when long
    if pt["total"]:
        block = [bold(esc(s["patches"].format(n=pt["total"])))]
        for status in ("MISSING", "UNKNOWN", "UPSTREAMED", "OK", "N/A"):
            group = [r for r in pt["rows"] if r["status"] == status]
            if not group:
                continue
            items = []
            for r in group:
                item = "• " + esc(r["label"])
                if r.get("reason"):
                    item += " — " + esc(s.get("r_" + r["reason"], r["reason"]))
                ref = _issue_ref(r.get("upstream"))
                if ref:
                    item += (f' <a href="{html.escape(r["upstream"])}">{esc(ref)}</a>'
                             if tg and r["upstream"].startswith("http") else f" {esc(ref)}")
                items.append(item)
            block.append(esc(s["g_" + status].format(n=len(group))))
            if tg and status in ("OK", "N/A") and len(items) > 15:
                block.append("<blockquote expandable>" + "\n".join(items) + "</blockquote>")
            else:
                block.extend(items)
        sections.append("\n".join(block))
    else:
        sections.append(bold(esc(s["no_patches"])))

    # 4. notes, one line
    parts = [s["n_new"].format(n=nt["new_30d"])]
    if nt["stale"]:
        parts.append(s["n_stale"].format(n=nt["stale"]))
    if nt["unconfirmed"]:
        parts.append(s["n_unc"].format(n=nt["unconfirmed"]))
    sections.append(bold(esc(s["notes"].format(n=nt["total"]))) + " · " + esc(" · ".join(parts)))

    legend = esc(s["legend"])
    sections.append(f"<i>{legend}</i>" if tg else (f"_{legend}_" if fmt == "md" else legend))
    content = "\n\n".join(sections)

    footer = s["footer"].format(when=_fmt_dt(ctx, parse_ts(report["generated_at"])))
    lint_n = report["lint"]["errors"]
    if lint_n:
        footer += s["footer_lint"].format(n=lint_n)
    footer = f"<i>{esc(footer)}</i>" if tg else (f"_{footer}_" if fmt == "md" else footer)
    text = content + "\n" + footer

    # Telegram allows 4096 characters; fold the longest group if needed
    limit = 4000
    if len(text) > limit:
        cut = text[:limit]
        cut = cut[:cut.rfind("\n")]
        if cut.count("<blockquote") > cut.count("</blockquote>"):
            cut += "</blockquote>"
        text = cut + "\n…\n" + footer
    return text, hashlib.sha256(content.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Telegram transport and the publish state machine
# ---------------------------------------------------------------------------

class TelegramError(Exception):
    def __init__(self, description, code=None, retry_after=None, uncertain=False):
        super().__init__(description)
        self.description, self.code, self.retry_after, self.uncertain = description, code, retry_after, uncertain


class BotApi:
    """Minimal Bot API client. `call` returns the `result` or raises TelegramError."""

    def __init__(self, token, timeout=20):
        self.token, self.timeout = token, timeout

    def call(self, method, payload):
        req = urllib.request.Request(f"https://api.telegram.org/bot{self.token}/{method}",
                                     data=json.dumps(payload).encode("utf-8"),
                                     headers={"Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                body = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            try:
                body = json.loads(exc.read().decode("utf-8"))
            except Exception:  # noqa: BLE001
                body = {"description": f"HTTP {exc.code}"}
            retry = (body.get("parameters") or {}).get("retry_after")
            raise TelegramError(self._mask(body.get("description") or f"HTTP {exc.code}"), exc.code, retry)
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            # The request may or may not have reached Telegram.
            raise TelegramError(self._mask(f"network: {type(exc).__name__}"), None, None, uncertain=True)
        if not body.get("ok"):
            raise TelegramError(self._mask(body.get("description") or "not ok"), body.get("error_code"))
        return body.get("result")

    def _mask(self, text):
        return str(text).replace(self.token, "<token>") if self.token else str(text)


def dashboard_target(ctx):
    d = ctx.cfg.get("dashboard") or {}
    token = read_env_value(ctx.home, str(d.get("bot_token_env") or "TELEGRAM_BOT_TOKEN"))
    chat = str(d.get("chat_id") or "").strip()
    if chat:
        thread = str(d.get("thread_id") or "").strip()
    else:
        chat = read_env_value(ctx.home, "TELEGRAM_HOME_CHANNEL")
        thread = read_env_value(ctx.home, "TELEGRAM_HOME_CHANNEL_THREAD_ID")
    return token, chat, thread


def _chat_value(chat):
    return int(chat) if re.match(r"^-?\d+$", chat) else chat


def publish(ctx, state, text, content_hash, api, save, force=False):
    """Send / pin / edit the dashboard message. Returns a list of alert events."""
    d = ctx.cfg.get("dashboard") or {}
    token, chat, thread = dashboard_target(ctx)
    if not token or not chat:
        raise FieldNotesError("dashboard needs a bot token and a chat id (see references/dashboard.md)")
    bot_id = token.split(":", 1)[0]
    profile = ctx.home.name
    key = f"{profile}|{bot_id}|{chat}|{thread}"
    entry = state["dashboard"].setdefault(key, {})
    now = now_utc()
    fresh_h = float(d.get("freshness_hours") or 6)
    events = []
    base = {"chat_id": _chat_value(chat)}
    entry["last_action"] = "unchanged"

    published = parse_ts(entry.get("published_at"))
    if (not force and entry.get("message_id") and entry.get("content_hash") == content_hash
            and published and (now - published).total_seconds() < fresh_h * 3600
            and (entry.get("pinned") or not d.get("pin", True))):
        return events  # nothing changed: zero requests

    uncertain = parse_ts(entry.get("send_uncertain_at"))
    if not entry.get("message_id") and uncertain and (now - uncertain).total_seconds() < fresh_h * 3600 and not force:
        return events

    def attempt(method, payload):
        for i in range(2):
            try:
                return api.call(method, payload)
            except TelegramError as exc:
                if exc.code == 429 and exc.retry_after and exc.retry_after <= 30 and i == 0:
                    time.sleep(exc.retry_after)
                    continue
                if (exc.code or 0) >= 500 and i == 0:
                    time.sleep(2)
                    continue
                raise
        return None

    def fail(exc):
        entry["failures"] = int(entry.get("failures") or 0) + 1
        entry["last_error"] = exc.description
        entry.setdefault("failing_since", iso(now))
        save()
        events.append({"kind": "bot_failing", "err": exc.description, "throttle": f"bot:{key}"})

    def send():
        payload = {**base, "text": text, "parse_mode": "HTML", "disable_notification": True,
                   "link_preview_options": {"is_disabled": True}}
        if thread:
            payload["message_thread_id"] = int(thread)
        try:
            result = attempt("sendMessage", payload)
        except TelegramError as exc:
            if exc.uncertain:
                entry["send_uncertain_at"] = iso(now)
                save()
                events.append({"kind": "send_uncertain", "h": int(fresh_h), "throttle": f"uncertain:{key}"})
            else:
                fail(exc)
            return False
        entry.update(message_id=result["message_id"], pinned=False, content_hash=content_hash,
                     published_at=iso(now), failures=0, last_action="sent")
        entry.pop("send_uncertain_at", None)
        entry.pop("failing_since", None)
        save()  # store the id at once: a later failure must not cause a second message
        return True

    if not entry.get("message_id"):
        if not send():
            return events
    elif entry.get("content_hash") != content_hash or force or not published \
            or (now - published).total_seconds() >= fresh_h * 3600:
        payload = {**base, "message_id": entry["message_id"], "text": text, "parse_mode": "HTML",
                   "link_preview_options": {"is_disabled": True}}
        try:
            attempt("editMessageText", payload)
            entry.update(content_hash=content_hash, published_at=iso(now), failures=0, last_action="edited")
            entry.pop("failing_since", None)
            save()
        except TelegramError as exc:
            desc = exc.description.lower()
            if "not modified" in desc:
                entry.update(content_hash=content_hash, published_at=iso(now), failures=0)
                save()
            elif "not found" in desc or "message_id_invalid" in desc or "can't be edited" in desc:
                entry.pop("message_id", None)
                entry["pinned"] = False
                save()
                if not send():
                    return events
                entry["last_action"] = "recreated"
                events.append({"kind": "dash_recreated"})
            else:
                fail(exc)
                return events

    if d.get("pin", True) and entry.get("message_id") and not entry.get("pinned"):
        try:
            attempt("pinChatMessage", {**base, "message_id": entry["message_id"], "disable_notification": True})
            entry["pinned"] = True
            save()
        except TelegramError as exc:
            events.append({"kind": "pin_failed", "err": exc.description, "throttle": f"pin:{key}"})
    return events


# ---------------------------------------------------------------------------
# doctor and events
# ---------------------------------------------------------------------------

def collect(ctx, state=None):
    """Everything doctor/dashboard need, without writing anything."""
    notes = load_notes(ctx)
    core = core_info(ctx)
    results = check_patches(ctx, notes, core) if core.get("exists") else []
    drift = compute_drift(ctx, core, results)
    items = lint(ctx, notes, core)
    return notes, core, results, drift, items


def diff_events(state, core, results, drift, notes):
    """Alert events for what changed since the previous check (also updates last_check)."""
    events = []
    last = state.get("last_check") or {}
    prev_status = last.get("patches") or {}
    by_id = {n.id: n for n in notes}
    first_run = not last
    for r in results:
        old = prev_status.get(r["id"])
        new = r["status"]
        if new in ("MISSING", "UNKNOWN", "UPSTREAMED") and old != new:
            note = by_id.get(r["id"])
            events.append({"kind": f"patch_{new}", "p": r["short"], "reason": r.get("reason") or "",
                           "cmd": str(note.get("patch_script") or "") if note else ""})
        elif new == "OK" and old in ("MISSING", "UNKNOWN", "UPSTREAMED"):
            events.append({"kind": "patch_back", "p": r["short"]})
    prev_unreg = set(last.get("drift_unregistered") or [])
    unreg = set(drift.get("unregistered") or []) if drift.get("available") else prev_unreg
    new_files = sorted(unreg - prev_unreg)
    if new_files:
        events.append({"kind": "drift_new", "files": ", ".join(new_files[:5]) + ("…" if len(new_files) > 5 else "")})
    elif prev_unreg and not unreg and not first_run:
        events.append({"kind": "drift_clear"})
    state["last_check"] = {"at": iso(now_utc()), "identity": core.get("identity"),
                           "patches": {r["id"]: r["status"] for r in results},
                           "drift_unregistered": sorted(unreg)}
    return events


def format_events(ctx, state, events):
    """Localised alert lines; throttled events are dropped while within alerts.repeat_hours."""
    s = STRINGS[ctx.lang]
    repeat = float((ctx.cfg.get("alerts") or {}).get("repeat_hours") or 24) * 3600
    now = now_utc()
    lines = []
    for ev in events:
        key = ev.get("throttle")
        if key:
            last = parse_ts(state["alerts"].get(key))
            if last and (now - last).total_seconds() < repeat:
                continue
            state["alerts"][key] = iso(now)
        template = s.get("a_" + ev["kind"])
        if not template:
            continue
        values = {k: v for k, v in ev.items() if k != "kind"}
        if ev["kind"] == "patch_MISSING":
            script = ev.get("cmd")
            base = str(ctx.cfg.get("patch_scripts_base") or "")
            if script and base and not os.path.isabs(script):
                script = str(Path(base) / script)
            values["cmd"] = f"python3 {script}" if script else s["cmd_none"]
        try:
            lines.append(template.format(**values))
        except (KeyError, IndexError):
            lines.append(template)
    return lines


# ---------------------------------------------------------------------------
# issue draft and migration
# ---------------------------------------------------------------------------

MASKS = [
    (re.compile(r"/home/[^/\s]+"), "~"),
    (re.compile(r"/Users/[^/\s]+"), "~"),
    (re.compile(r"[A-Za-z]:\\Users\\[^\\\s]+", re.IGNORECASE), "~"),
    (re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"), "<ip>"),
    (re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+"), "<email>"),
    (re.compile(r"-100\d{6,}"), "<chat_id>"),
]


def mask(text):
    for _, pattern in SECRET_PATTERNS:
        text = pattern.sub("<redacted>", text)
    for pattern, repl in MASKS:
        text = pattern.sub(repl, text)
    return text


def _sections(body):
    out, current = {}, None
    for line in body.split("\n"):
        m = re.match(r"^##\s+(.*)$", line)
        if m:
            current = m.group(1).strip().lower()
            out[current] = []
        elif current is not None:
            out[current].append(line)
    return {k: "\n".join(v).strip() for k, v in out.items()}


def _pick(sections, *names):
    for key, value in sections.items():
        if any(key.startswith(n) for n in names) and value:
            return value
    return ""


def issue_draft(note, core):
    sec = _sections(note.body)
    parts = [
        "<!-- DRAFT made by hermes-field-notes. Nothing was posted. Read every line before publishing: "
        "masking catches obvious secrets, paths and addresses only. -->",
        f"## {note.title}", "",
        f"**Hermes version:** {display_version(core)} ({core.get('short') or 'unknown'})", "",
        "### Symptom", _pick(sec, "symptom", "симптом") or "_describe what you saw_", "",
        "### Root cause", _pick(sec, "root cause", "причина") or "_not established_", "",
        "### How to reproduce / verify", _pick(sec, "how to verify", "как проверить", "проверка") or "_steps_", "",
        "### Workaround", _pick(sec, "fix", "workaround", "фикс", "обход") or "_none_", "",
    ]
    return mask("\n".join(parts).rstrip() + "\n")


_STATUS_MAP = {"fixed locally": "workaround", "workaround": "workaround", "needs verification": "needs-verification",
               "obsolete": "obsolete", "promoted to skill": "promoted", "promoted": "promoted", "active": "active",
               "deferred": "active", "fixed": "workaround", "fixed upstream": "fixed-upstream"}


def _map_status(raw):
    raw = str(raw or "").strip().lower()
    for key, value in _STATUS_MAP.items():
        if raw.startswith(key):
            return value
    return "active"


def _map_area(raw):
    for token in re.split(r"[|,/ ]+", str(raw or "").lower()):
        if token in AREAS:
            return token
        if token in ("telegram", "line", "discord", "slack", "whatsapp"):
            return "platform"
    return "other"


def migrate_note(path, index_rows):
    """(new_text, problems) for one legacy note: field-notes bullet header or older YAML frontmatter."""
    text = Path(path).read_text(encoding="utf-8").replace("\r\n", "\n").lstrip("\ufeff")
    stem = Path(path).stem
    problems = []
    meta, order, body, errors = split_frontmatter(text) if text.startswith("---\n") else ({}, [], text, [])
    if errors:
        problems.extend(errors)
    if not meta:
        m = re.search(r"\*\*Date:\*\*\s*([\d-]+).*?\*\*Area:\*\*\s*([^·\n]+).*?\*\*Status:\*\*\s*([^·\n]+)", text)
        title = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
        meta = {"title": title.group(1).strip() if title else stem}
        if m:
            meta.update(date=m.group(1), area_raw=m.group(2).strip(), status_raw=m.group(3).strip())
        body = text
    new = {"schema_version": SCHEMA_VERSION, "id": stem,
           "title": str(meta.get("title") or stem),
           "date": str(meta.get("date") or stem[:10]),
           "updated": str(meta.get("updated") or meta.get("date") or stem[:10]),
           "type": meta.get("type") if meta.get("type") in TYPES else "pitfall",
           "area": meta.get("area") if meta.get("area") in AREAS else _map_area(meta.get("area") or meta.get("area_raw")),
           "status": meta.get("status") if meta.get("status") in STATUSES else _map_status(meta.get("status") or meta.get("status_raw")),
           "seen_on": str(meta.get("seen_on") or ""),
           "summary": str(meta.get("summary") or index_rows.get(stem) or "")}
    if not new["summary"]:
        problems.append("no summary found — write one")
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", new["date"]):
        problems.append(f"date '{new['date']}' is not YYYY-MM-DD")
    for key, value in meta.items():
        if key not in new and key not in ("area_raw", "status_raw"):
            new[key] = value  # keep unknown fields as they were
    if meta.get("area") and meta.get("area") not in AREAS:
        new["legacy_area"] = str(meta.get("area"))
    if meta.get("status") and meta.get("status") not in STATUSES:
        new["legacy_status"] = str(meta.get("status"))
    for key in ("area_raw", "status_raw"):
        if meta.get(key):
            new["legacy_" + key[:-4]] = meta[key]
    return dump_frontmatter(new) + ("\n" if not body.startswith("\n") else "") + body, problems


def _index_summaries(index_path):
    rows = {}
    try:
        lines = Path(index_path).read_text(encoding="utf-8").splitlines()
    except OSError:
        return rows
    for line in lines:
        m = re.search(r"\]\((?:notes/)?([^)]+?)\.md\)", line)
        if m and line.startswith("|"):
            cells = [c.strip() for c in re.split(r"(?<!\\)\|", line.strip().strip("|"))]
            if cells:
                rows[Path(m.group(1)).name] = cells[-1].replace("\\|", "|")
    return rows


# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------

def out_json(data):
    print(json.dumps(data, ensure_ascii=False, indent=1, default=str))


def cmd_root(ctx, args):
    print(ctx.store)
    return EXIT_OK


def cmd_init(ctx, args):
    ctx.require_writable("create the store")
    ctx.notes_dir.mkdir(parents=True, exist_ok=True)
    index = ctx.store / "INDEX.md"
    if not index.is_file():
        atomic_write(index, render_index([], ""))
        print(f"created {index}")
    print(ctx.store)
    return EXIT_OK


def _similar(notes, title, limit=3):
    words = set(_tokens(title))
    scored = []
    for n in notes:
        other = set(_tokens(n.title + " " + str(n.get("summary") or "")))
        if words and other:
            j = len(words & other) / len(words | other)
            if j >= 0.15:
                scored.append((j, n))
    return [n for _, n in sorted(scored, key=lambda x: -x[0])[:limit]]


def cmd_new(ctx, args):
    require_store(ctx)
    ctx.require_writable("create a note")
    slug = args.slug.strip().lower()
    if not re.match(r"^[a-z0-9][a-z0-9-]{1,60}$", slug):
        raise FieldNotesError("slug: lowercase latin letters, digits and '-', 2–61 characters")
    if args.type not in TYPES:
        raise FieldNotesError(f"--type must be one of {', '.join(TYPES)}")
    if args.area not in AREAS:
        raise FieldNotesError(f"--area must be one of {', '.join(AREAS)}")
    notes = load_notes(ctx)
    same = [n for n in notes if n.id[11:] == slug]
    if same:
        print(f"a note with this slug exists: {same[0].path} — update it instead of adding a new one",
              file=sys.stderr)
        return EXIT_UNKNOWN
    similar = _similar(notes, args.title)
    if similar and not args.force:
        print("similar notes exist — update one of them, or re-run with --force:", file=sys.stderr)
        for n in similar:
            print(f"  {n.path}  {n.title}", file=sys.stderr)
        return EXIT_UNKNOWN
    today = ctx.today().isoformat()
    note_id = f"{today}-{slug}"
    core = core_info(ctx)
    template = ASSETS / ("patch-note-template.md" if args.type == "patch" else "note-template.md")
    text = template.read_text(encoding="utf-8")
    values = {"id": note_id, "date": today, "title": args.title.replace('"', "'"), "type": args.type,
              "area": args.area, "seen_on": display_version(core) if core.get("exists") else "",
              "identity": core.get("short") or ""}
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", value)
    path = ctx.notes_dir / f"{note_id}.md"
    atomic_write(path, text)
    print(path)
    if args.type == "patch":
        checks = ctx.notes_dir / f"{note_id}.checks.json"
        atomic_write(checks, (ASSETS / "patch-checks.example.json").read_text(encoding="utf-8"))
        print(checks)
    print("next: fill it in, then `fieldnotes.py index` and `fieldnotes.py lint`", file=sys.stderr)
    return EXIT_OK


def cmd_index(ctx, args):
    require_store(ctx)
    ctx.require_writable("write INDEX.md")
    notes = load_notes(ctx)
    path = ctx.store / "INDEX.md"
    current = path.read_text(encoding="utf-8") if path.is_file() else ""
    text = render_index(notes, current)
    if text != current.replace("\r\n", "\n"):
        atomic_write(path, text)
        print(f"INDEX.md: {len(notes)} notes")
    else:
        print(f"INDEX.md is up to date ({len(notes)} notes)")
    return EXIT_OK


def cmd_lint(ctx, args):
    require_store(ctx)
    notes = load_notes(ctx)
    items = lint(ctx, notes, core_info(ctx))
    if args.json:
        out_json([{"level": a, "where": b, "message": c} for a, b, c in items])
    else:
        for level, where, msg in items:
            print(f"{level:5} {where}: {msg}")
        errors = sum(1 for i in items if i[0] == "error")
        print(f"lint: {len(notes)} notes · {errors} errors · "
              f"{sum(1 for i in items if i[0] == 'warn')} warnings · {sum(1 for i in items if i[0] == 'stale')} stale")
    return EXIT_ERR if any(i[0] == "error" for i in items) else EXIT_OK


def cmd_search(ctx, args):
    notes = load_notes(ctx) if ctx.notes_dir.is_dir() else []
    hits, n_notes, n_known = search(notes, args.terms, args.limit)
    if args.json:
        out_json([{"source": kind, "path": str(item.path) if kind == "note" else None,
                   "title": item.title if kind == "note" else item[0],
                   "status": item.status if kind == "note" else None,
                   "summary": str(item.get("summary")) if kind == "note" else item[1][:300]}
                  for _, kind, item in hits])
        return EXIT_OK
    if not hits:
        print(f"0 matches in {n_notes} notes and {n_known} known pitfalls for: {' '.join(args.terms)}")
        return EXIT_OK
    for _, kind, item in hits:
        if kind == "note":
            print(f"[{item.status}] {item.path}\n    {item.title}\n    {item.get('summary')}")
        else:
            symptom = re.search(r"\*\*Symptom:\*\*\s*(.+)", item[1])
            print(f"[known pitfall] {item[0]}\n    {symptom.group(1) if symptom else ''}\n"
                  f"    see {KNOWN_PITFALLS.name} (skill references)")
    print(f"-- {len(hits)} match(es) in {n_notes} notes and {n_known} known pitfalls")
    return EXIT_OK


def cmd_patches(ctx, args):
    require_store(ctx)
    notes = load_notes(ctx)
    core = core_info(ctx)
    if args.action == "list":
        rows = [n for n in notes if n.is_patch]
        if args.json:
            out_json([{"id": n.id, "short": n.get("patch_short"), "kind": n.get("patch_kind"), "status": n.status,
                       "upstream": n.get("upstream")} for n in rows])
        else:
            for n in rows:
                print(f"{n.status:18} {str(n.get('patch_kind') or '?'):13} {n.get('patch_short') or n.title}  ({n.id})")
            print(f"-- {len(rows)} patch notes, {sum(1 for n in rows if n.is_live)} live")
        return EXIT_OK
    if not core["exists"]:
        raise FieldNotesError(f"Hermes core not found at {ctx.hermes_root} (--hermes-root)", EXIT_NOTFOUND)
    results = check_patches(ctx, notes, core)
    if args.json:
        out_json({"core": {"version": display_version(core), "identity": core.get("identity")}, "patches": results})
    else:
        print(f"core {display_version(core)} ({core.get('short')}) at {core['root']} — static check, the tree on disk")
        for r in sorted(results, key=lambda r: STATUS_ORDER.get(r["status"], 9)):
            reason = f" ({r['reason']})" if r.get("reason") else ""
            print(f"{STATUS_ICON[r['status']]} {r['status']}{reason}  {r['short']}  [{r['id']}]")
            if r["status"] != "OK" or args.verbose:
                for e in r["evidence"]:
                    print(f"      {e}")
        c = {k: sum(1 for r in results if r["status"] == k) for k in STATUS_ICON}
        print(f"-- {len(results)} live patches: {c['OK']} OK · {c['MISSING']} MISSING · {c['UNKNOWN']} UNKNOWN · "
              f"{c['UPSTREAMED']} UPSTREAMED · {c['N/A']} N/A  (OK = signs in place, not proof it works)")
    return patches_exit(results)


def cmd_drift(ctx, args):
    require_store(ctx)
    notes = load_notes(ctx)
    core = core_info(ctx)
    drift = compute_drift(ctx, core, check_patches(ctx, notes, core) if core["exists"] else [])
    if args.json:
        out_json(drift)
        return EXIT_OK
    if not drift["available"]:
        print(f"drift: not checked — {drift['reason']}")
        return EXIT_OK
    print(f"changed tracked files: {len(drift['changed'])} · covered by patch notes: {len(drift['registered'])} · "
          f"NOT covered: {len(drift['unregistered'])} · untracked: {len(drift['untracked'])}"
          + (f" · local commits on top of {drift['tag']}: {drift['ahead']}" if drift.get("ahead") else ""))
    for p in drift["unregistered"]:
        print(f"  ⚠️ {p}")
    for p in drift["registered"]:
        print(f"  ·  {p} (has a patch note; its other edits are not verified)")
    return EXIT_OK


def cmd_doctor(ctx, args):
    require_store(ctx)
    with Lock(ctx.lock_path) if not ctx.read_only else _nolock():
        state = load_state(ctx)
        notes, core, results, drift, items = collect(ctx, state)
        events = []
        if state.get("_recovered"):
            events.append({"kind": "state_recovered", "msg": state["_recovered"]})
        ev = record_core(state, core, now_utc())
        if ev:
            events.insert(0, ev)
        if core.get("exists"):
            events.extend(diff_events(state, core, results, drift, notes))
        upstream, up_events = upstream_info(ctx, state, core)
        events.extend(up_events)
        save_state(ctx, state)
    report = build_report(ctx, state, notes, core, results, drift, items, upstream)
    if args.json:
        out_json({"report": report, "events": events, "patches": results, "lint": items})
        return patches_exit(results)
    text, _ = render(ctx, report, "text")
    print(text)
    if events:
        print("\nchanges since the last check:")
        for line in format_events(ctx, {"alerts": {}}, events):
            print("  " + line)
    code = patches_exit(results)
    verdict = {EXIT_OK: "all live patches have their signs in place",
               EXIT_MISSING: "a patch is MISSING — re-apply it (with the owner's consent)",
               EXIT_UNKNOWN: "a patch check is UNKNOWN — read its evidence (`patches check`)"}[code]
    if drift.get("available") and drift.get("unregistered"):
        verdict += "; core files changed outside the registry"
    print(f"\ndoctor: {verdict}")
    return code


class _nolock:
    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False


def cmd_dashboard(ctx, args):
    require_store(ctx)
    if args.publish:
        ctx.require_writable("publish the dashboard")
    with Lock(ctx.lock_path) if args.publish else _nolock():
        state = load_state(ctx)
        notes, core, results, drift, items = collect(ctx, state)
        if not ctx.read_only and args.publish:
            record_core(state, core, now_utc())
        upstream, _ = upstream_info(ctx, state, core)
        report = build_report(ctx, state, notes, core, results, drift, items, upstream)
        fmt = "telegram" if args.publish else args.format
        text, digest = render(ctx, report, fmt)
        if not args.publish:
            print(text)
            return EXIT_OK
        token, _, _ = dashboard_target(ctx)
        events = publish(ctx, state, text, digest, BotApi(token), lambda: save_state(ctx, state), force=args.force)
        lines = format_events(ctx, state, events)
        save_state(ctx, state)
    for line in lines:
        print(line)
    entry = next((v for k, v in state["dashboard"].items() if k.endswith("|" + "|".join(dashboard_target(ctx)[1:]))), {})
    print(f"dashboard: {entry.get('last_action', '?')} · message {entry.get('message_id', '—')} · "
          f"pinned {bool(entry.get('pinned'))}")
    return EXIT_OK


def cmd_tick(ctx, args):
    """One cron tick: doctor + dashboard. Prints alert lines only; silence when nothing changed."""
    lines = []
    with Lock(ctx.lock_path):
        state = load_state(ctx)
        if not ctx.notes_dir.is_dir():
            lines = format_events(ctx, state, [{"kind": "no_store", "root": str(ctx.store), "throttle": "no-store"}])
            save_state(ctx, state)
            for line in lines:
                print(line)
            return EXIT_OK
        notes, core, results, drift, items = collect(ctx, state)
        events = []
        if not core.get("exists"):
            events.append({"kind": "core_missing", "root": str(ctx.hermes_root), "throttle": "core-missing"})
        if state.get("_recovered"):
            events.append({"kind": "state_recovered", "msg": state["_recovered"]})
        ev = record_core(state, core, now_utc())
        if ev:
            events.insert(0, ev)
        if core.get("exists"):
            events.extend(diff_events(state, core, results, drift, notes))
        upstream, up_events = upstream_info(ctx, state, core)
        events.extend(up_events)
        save_state(ctx, state)
        d = ctx.cfg.get("dashboard") or {}
        if d.get("enabled"):
            report = build_report(ctx, state, notes, core, results, drift, items, upstream)
            text, digest = render(ctx, report, "telegram")
            token, chat, _ = dashboard_target(ctx)
            if not token or not chat:
                events.append({"kind": "bot_failing", "err": "no bot token or chat id", "throttle": "dash-config"})
            else:
                try:
                    events.extend(publish(ctx, state, text, digest, BotApi(token), lambda: save_state(ctx, state)))
                except FieldNotesError as exc:
                    events.append({"kind": "bot_failing", "err": str(exc), "throttle": "dash-config"})
        lines = format_events(ctx, state, events)
        save_state(ctx, state)
    for line in lines:
        print(line)
    return EXIT_OK


def cmd_issue(ctx, args):
    require_store(ctx)
    path = ctx.notes_dir / f"{args.id}.md"
    if not path.is_file():
        matches = [n for n in load_notes(ctx) if n.id.endswith(args.id)]
        if len(matches) != 1:
            raise FieldNotesError(f"note not found or ambiguous: {args.id}", EXIT_NOTFOUND)
        path = matches[0].path
    print(issue_draft(Note(path), core_info(ctx)))
    return EXIT_OK


def cmd_migrate(ctx, args):
    src = Path(args.source).expanduser()
    notes_src = src / "notes" if (src / "notes").is_dir() else src
    files = sorted(p for p in notes_src.glob("*.md") if p.name.upper() not in ("INDEX.MD", "README.MD"))
    if not files:
        raise FieldNotesError(f"no notes found in {notes_src}", EXIT_NOTFOUND)
    rows = _index_summaries(src / "INDEX.md")
    apply = args.apply and not ctx.read_only
    if apply:
        ctx.notes_dir.mkdir(parents=True, exist_ok=True)
    stats = {"new": 0, "same": 0, "conflict": 0}
    for path in files:
        text, problems = migrate_note(path, rows)
        dest = ctx.notes_dir / path.name
        if dest.resolve() == path.resolve():
            state = "in place"
            if apply and text != path.read_text(encoding="utf-8").replace("\r\n", "\n"):
                atomic_write(dest, text)
                state = "rewritten in place"
            stats["new"] += 1
        elif dest.is_file():
            current = dest.read_text(encoding="utf-8").replace("\r\n", "\n")
            if current == text:
                state = "already migrated"
                stats["same"] += 1
            else:
                state = "CONFLICT: a different note with this name exists — left alone"
                stats["conflict"] += 1
        else:
            state = "new"
            stats["new"] += 1
            if apply:
                atomic_write(dest, text)
        extra = f" · {'; '.join(problems)}" if problems else ""
        print(f"{path.name}: {state}{extra}")
        for sidecar in path.parent.glob(path.stem + ".checks.json"):
            if apply and not (ctx.notes_dir / sidecar.name).exists():
                atomic_write(ctx.notes_dir / sidecar.name, sidecar.read_text(encoding="utf-8"))
    print(f"-- {len(files)} notes: {stats['new']} to write · {stats['same']} already there · "
          f"{stats['conflict']} conflicts" + ("" if apply else " · dry run, nothing written (add --apply)"))
    if apply:
        notes = load_notes(ctx)
        index = ctx.store / "INDEX.md"
        current = index.read_text(encoding="utf-8") if index.is_file() else ""
        atomic_write(index, render_index(notes, current))
    return EXIT_ERR if stats["conflict"] else EXIT_OK


def build_parser():
    ap = argparse.ArgumentParser(prog="fieldnotes.py", description=__doc__.split("\n\n")[0])
    ap.add_argument("--version", action="version", version=f"hermes-field-notes {VERSION}")
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--hermes-home", help="Hermes home (default: $HERMES_HOME or ~/.hermes)")
    common.add_argument("--config", help="config file (default: <hermes-home>/field-notes.json)")
    common.add_argument("--root", help="notes store (default: <hermes-home>/field-notes)")
    common.add_argument("--hermes-root", help="hermes-agent checkout (default: <hermes-home>/hermes-agent)")
    common.add_argument("--read-only", action="store_true", help="write nothing, use no network")
    common.add_argument("--json", action="store_true", help="machine-readable output")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("root", parents=[common], help="print the store path").set_defaults(fn=cmd_root)
    sub.add_parser("init", parents=[common], help="create an empty store").set_defaults(fn=cmd_init)
    p = sub.add_parser("new", parents=[common], help="new note from the template")
    p.add_argument("slug")
    p.add_argument("--type", default="pitfall", choices=TYPES)
    p.add_argument("--area", default="other", choices=AREAS)
    p.add_argument("--title", required=True)
    p.add_argument("--force", action="store_true", help="create even if similar notes exist")
    p.set_defaults(fn=cmd_new)
    sub.add_parser("index", parents=[common], help="regenerate INDEX.md").set_defaults(fn=cmd_index)
    sub.add_parser("lint", parents=[common], help="check notes and the index").set_defaults(fn=cmd_lint)
    p = sub.add_parser("search", parents=[common], help="search notes and known pitfalls")
    p.add_argument("terms", nargs="+")
    p.add_argument("--limit", type=int, default=10)
    p.set_defaults(fn=cmd_search)
    p = sub.add_parser("patches", parents=[common], help="list patches, or check them against the core")
    p.add_argument("action", nargs="?", default="list", choices=("list", "check"))
    p.add_argument("-v", "--verbose", action="store_true")
    p.set_defaults(fn=cmd_patches)
    sub.add_parser("drift", parents=[common], help="core changes and their coverage").set_defaults(fn=cmd_drift)
    sub.add_parser("doctor", parents=[common], help="core + patches + drift + notes to re-verify").set_defaults(fn=cmd_doctor)
    p = sub.add_parser("dashboard", parents=[common], help="render the dashboard, or publish it to Telegram")
    p.add_argument("--format", default="text", choices=("telegram", "md", "text"))
    p.add_argument("--publish", action="store_true")
    p.add_argument("--force", action="store_true", help="edit the message even if nothing changed")
    p.set_defaults(fn=cmd_dashboard)
    sub.add_parser("tick", parents=[common], help="cron tick (used by fieldnotes-watch.py)").set_defaults(fn=cmd_tick)
    p = sub.add_parser("issue-draft", parents=[common], help="upstream issue draft from a note (stdout)")
    p.add_argument("id")
    p.set_defaults(fn=cmd_issue)
    p = sub.add_parser("migrate", parents=[common], help="import notes of the older formats")
    p.add_argument("--from", dest="source", required=True)
    p.add_argument("--apply", action="store_true")
    p.set_defaults(fn=cmd_migrate)
    return ap


def main(argv=None):
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass
    args = build_parser().parse_args(argv)
    try:
        ctx = Context(args)
        return args.fn(ctx, args)
    except FieldNotesError as exc:
        print(f"fieldnotes: {exc}", file=sys.stderr)
        return exc.code


if __name__ == "__main__":
    raise SystemExit(main())
